version: '3.8'

services:
  bookcar-backend:
    image: ${DOCKER_USERNAME:-tinh08042005}/bookcar-backend:${IMAGE_TAG:-latest}
    container_name: bookcar-backend-v1
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_URL=${REDIS_URL}
      - SPRING_DATA_REDIS_DATABASE=${REDIS_DATABASE}
    restart: unless-stopped