version: '3.8'

services:
  ridebook-backend:
    image: ${DOCKER_USERNAME:-tinh08042005}/ridebook-backend:${IMAGE_TAG:-latest}
    container_name: ridebook-backend-v1
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_URL=${REDIS_URL}
      - SPRING_DATA_REDIS_DATABASE=${REDIS_DATABASE}
    networks:
      - shared-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s


networks:
  shared-network:
    external: true