name: CD Pipeline
run-name: ${{ github.actor }}
on:
  workflow_run: 
    workflows:
      - "CI Pipeline" 
    types: 
      - completed 
    branches: ['main','master','test']

jobs: 
  deploy-backend: 
    name: Deploy Backend 
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_ROOT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "Backend/docker-compose.yml"
          target: "/home/ec2-user/ridebook"
          strip_components: 1

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.SSH_ROOT }}
          username: ${{ secrets.SSH_USERNAME }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          port: 22
          script: |
            echo "Start Deploying EC2"
            # Sửa đường dẫn chuẩn cho Amazon Linux 2023
            mkdir -p /home/ec2-user/ridebook
            cd /home/ec2-user/ridebook
            
            # Ghi mã định danh phiên bản code
            echo "IMAGE_TAG=${{ github.event.workflow_run.head_sha }}" > .env
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
            
            # Ghi toàn bộ nội dung file .env từ Github Secrets
            echo "${{ secrets.ENV_PROD }}" >> .env
            
            # Khởi động Docker Compose
            docker compose pull 
            docker compose up -d --force-recreate 
            
            # Dọn dẹp rác hệ thống để tránh đầy ổ cứng
            docker image prune -f 
            echo "Deploy Backend EC2 Successfully"


  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
